language: python
branches:
  only:
    - master
    - /^v\d\.\d+$/
    - /^v\d\.\d+\.\d+(rc\d+|\.dev\d+)?$/
matrix:
  include:
    - python: 3.8
      env: TOXENV=security
    - python: 3.8
      env: TOXENV=flake8
    - python: 2.7
      env: TOXENV=py27
    - python: pypy
      env: TOXENV=pypy
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: pypy3
      env: TOXENV=pypy3
    - python: 3.7
      env: TOXENV=docs
install:
  - pip install -U pip tox twine wheel codecov
script: tox
after_success:
  - codecov

notifications:
  irc:
    use_notice: true
    skip_join: true
    channels:
      - irc.freenode.org#scrapy

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scrapy
  password:
    secure: kY3UdcidDTnwfBY9gGeUDK7g9k9Weg+AEo1CJYdQ8fBYQkIQBubbTiu1UGqOb0v/btySZDidp/jsGPLxlTZ34sG9jQEiteQILHJMjLzgcNNTSBsf8VIqTxcLpxS+RgeB2MyITOvYhxNMI4ezMXkm9TH7jL60gv/4BtiMOTpFzr8=
  on:
    tags: true
    all_branches: true
    repo: scrapy/parsel
    condition: $TOXENV == py37
